language: python
python:
  - "3.7"
  - "3.6"

branches:
  only:
    - master
    - develop
    - release
    - develop-microsim

install:
  - pip install -r requirements.txt

script:
  - python setup.py install
  - coverage run -m unittest discover crime_sim_toolkit/tests/
  - coverage xml
  - python-codacy-coverage -r coverage.xml
